version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-1:860061945305:task-definition/orderManagement-TF-936099:6"
        LoadBalancerInfo:
          ContainerName: "payment"
          ContainerPort: "9004"
        PlatformVersion: "LATEST"