version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-1:860061945305:task-definition/orderManagement-TF-936099:8"
        LoadBalancerInfo:
          ContainerName: "auth"
          ContainerPort: "9001"
        PlatformVersion: "LATEST"